name: 'Deploy workflow'

on:
  push:
    branches:
      - '**'

env:
  QT_MIRROR: https://mirrors.ocf.berkeley.edu/qt/ # https://download.qt.io/static/mirrorlist/

jobs:
  Build-Linux-ARM64:
    runs-on: ubuntu-22.04-arm

    env:
      QT_VERSION: 6.6.2
      QIF_VERSION: 4.7

    steps:
    - name: Install Qt (Linux ARM64)
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'linux'
        target: 'desktop'
        arch: 'linux_arm64'
        modules: 'qtremoteobjects qt5compat qtshadertools'
        dir: ${{ runner.temp }}
        setup-python: 'true'
        set-env: 'true'
        extra: '--external 7z --base ${{ env.QT_MIRROR }}'

    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get install -y libxkbcommon-x11-0

    - name: Build project
      run: |
        export QT_BIN_DIR=${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/linux_arm64/bin
        export QIF_BIN_DIR=${{ runner.temp }}/Qt/Tools/QtInstallerFramework/${{ env.QIF_VERSION }}/bin
        bash deploy/build_linux.sh

    - name: Pack installer
      run: cd deploy && tar -cf AmneziaVPN_Linux_Installer_arm64.tar AmneziaVPN_Linux_Installer.bin

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AmneziaVPN_Linux_Installer_ARM64
        path: deploy/AmneziaVPN_Linux_Installer_arm64.tar
        retention-days: 7

  Extra:
    runs-on: ubuntu-latest
    steps:
      - name: Search a corresponding PR
        uses: octokit/request-action@v2.x
        id: pull_request
        with:
          route: GET /repos/${{ github.repository }}/pulls
          head: ${{ github.repository_owner }}:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add PR link to build summary
        if: ${{ fromJSON(steps.pull_request.outputs.data)[0].number != '' }}
        run: | 
          echo "Pull request:" >> $GITHUB_STEP_SUMMARY
          echo "[[#${{ fromJSON(steps.pull_request.outputs.data)[0].number }}] ${{ fromJSON(steps.pull_request.outputs.data)[0].title }}](${{ fromJSON(steps.pull_request.outputs.data)[0].html_url }})" >> $GITHUB_STEP_SUMMARY
